import { useCallback, useEffect, useMemo, useState } from 'react'
import { Banknote, CheckCircle2, WalletCards } from 'lucide-react'
import AdminModuleShell, { ModuleMetric } from '../../components/AdminModuleShell'
import { supabase } from '../../lib/supabase'
import type { DeliveryOrder, Rider } from '../../lib/types'

export default function CashFlowDashboard() {
  const [orders, setOrders] = useState<DeliveryOrder[]>([]), [riders, setRiders] = useState<Rider[]>([]), [handovers, setHandovers] = useState<any[]>([]); const [loading, setLoading] = useState(true); const today = new Date().toISOString().slice(0, 10)
  const load = useCallback(async () => { setLoading(true); const [o, r, h] = await Promise.all([supabase.from('delivery_orders').select('*').eq('delivery_date', today), supabase.from('riders').select('*').eq('status', 'active'), supabase.from('daily_cash_handovers').select('*').eq('handover_date', today)]); setOrders((o.data || []) as DeliveryOrder[]); setRiders((r.data || []) as Rider[]); setHandovers(h.data || []); setLoading(false) }, [today]); useEffect(() => { void load() }, [load])
  const rows = useMemo(() => riders.map(rider => { const ro = orders.filter(o => o.rider_id === rider.id && o.status === 'delivered' && String((o as any).payment_type || 'cash') === 'cash'); const expected = ro.reduce((s, o) => s + Number(o.invoice_amount || 0), 0); const handover = handovers.find(h => h.rider_id === rider.id); const actual = Number(handover?.actual_amount || ro.reduce((s, o) => s + Number((o as any).cash_collected || 0), 0)); const variance = actual - expected; return { rider, expected, actual, variance, count: ro.length, status: Math.abs(variance) < 1 ? 'balanced' : variance < 0 ? 'shortage' : 'excess' } }).filter(r => r.expected || r.actual).sort((a, b) => Math.abs(b.variance) - Math.abs(a.variance)), [orders, riders, handovers]); const expected = rows.reduce((s, r) => s + r.expected, 0), actual = rows.reduce((s, r) => s + r.actual, 0), variance = actual - expected
  return <AdminModuleShell title="التدفق النقدي اليومي" subtitle="المتوقع، المحصّل، وفروق عهدة كل دليفري" icon={<Banknote/>} loading={loading} onRefresh={load}><section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><ModuleMetric label="الكاش المتوقع" value={`${expected.toLocaleString('ar-EG')} ج`} hint={`${orders.filter(o => o.status === 'delivered').length} أوردر`} tone="sky"/><ModuleMetric label="تم تسليمه" value={`${actual.toLocaleString('ar-EG')} ج`} hint="عهد مسجلة"/><ModuleMetric label="الفارق" value={`${Math.abs(variance).toLocaleString('ar-EG')} ج`} hint={variance < 0 ? 'عجز' : variance > 0 ? 'زيادة' : 'متوازن'} tone={variance ? 'rose' : 'teal'}/><ModuleMetric label="تحتاج تسوية" value={rows.filter(r => r.status !== 'balanced').length} hint="دليفري" tone="amber"/></section><div className="mt-5 overflow-hidden rounded-[2rem] border bg-white shadow-sm"><div className="flex items-center gap-3 border-b p-5"><WalletCards className="text-teal-600"/><div><h2 className="font-black">تسوية الدليفري</h2><p className="text-xs font-bold text-slate-400">البيانات تظهر تلقائيًا بعد تطبيق Migration رقم 56</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4 text-right">الدليفري</th><th>أوردرات كاش</th><th>المتوقع</th><th>المحصّل</th><th>الفارق</th><th>الحالة</th></tr></thead><tbody>{rows.map(r => <tr key={r.rider.id} className="border-t"><td className="p-4 font-black">{r.rider.name}</td><td>{r.count}</td><td>{r.expected.toLocaleString('ar-EG')} ج</td><td className="font-black text-emerald-700">{r.actual.toLocaleString('ar-EG')} ج</td><td className={r.variance < 0 ? 'font-black text-rose-600' : 'font-black text-emerald-600'}>{r.variance.toLocaleString('ar-EG')} ج</td><td>{r.status === 'balanced' ? <span className="inline-flex items-center gap-1 text-emerald-700"><CheckCircle2 size={15}/> متوازن</span> : <span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-black text-amber-700">{r.status === 'shortage' ? 'عجز' : 'زيادة'}</span>}</td></tr>)}{!rows.length && <tr><td colSpan={6} className="p-12 text-center font-bold text-slate-400">لا توجد حركة كاش مسجلة اليوم</td></tr>}</tbody></table></div></div></AdminModuleShell>
}
