import { useCallback, useEffect, useMemo, useState } from 'react'
import { ShieldAlert } from 'lucide-react'
import AdminModuleShell, { ModuleMetric } from '../../components/AdminModuleShell'
import { supabase } from '../../lib/supabase'
import { getOperationalPeriod } from '../../lib/helpers'
import { detectFraudSignals } from '../../lib/deliveryIntelligence'
import type { DeliveryOrder, Rider } from '../../lib/types'

const labels = { duplicate_invoice: 'فاتورة متعددة', impossible_timing: 'توقيت غير منطقي', sequential_same_code: 'تكرار كود عميل' }
export default function FraudAlerts() {
  const period = useMemo(() => getOperationalPeriod(), []); const [orders, setOrders] = useState<DeliveryOrder[]>([]), [riders, setRiders] = useState<Rider[]>([]), [loading, setLoading] = useState(true), [resolved, setResolved] = useState<string[]>([])
  const load = useCallback(async () => { setLoading(true); const [o, r] = await Promise.all([supabase.from('delivery_orders').select('*').gte('delivery_date', period.start).lte('delivery_date', period.end), supabase.from('riders').select('*')]); setOrders((o.data || []) as DeliveryOrder[]); setRiders((r.data || []) as Rider[]); setLoading(false) }, [period]); useEffect(() => { void load() }, [load]); const signals = detectFraudSignals(orders, riders).filter(s => !resolved.includes(s.key)); const high = signals.filter(s => s.severity === 'high')
  async function resolve(key: string, signal: any) { setResolved(v => [...v, key]); await supabase.from('fraud_signals').insert({ order_id: signal.orderId || null, rider_id: signal.riderId, signal_type: signal.type, severity: signal.severity, description: signal.description, status: 'resolved', reviewed_at: new Date().toISOString(), resolution_notes: 'تمت المراجعة من مركز الحماية' }) }
  return <AdminModuleShell title="مركز الحماية وكشف الأنماط" subtitle="تحليل آلي لا يستبدل قرار الإدارة — كل إشارة تحتاج مراجعة بشرية" icon={<ShieldAlert/>} loading={loading} onRefresh={load}><section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><ModuleMetric label="إشارات مفتوحة" value={signals.length} hint="خلال الدورة" tone="amber"/><ModuleMetric label="عالية الخطورة" value={high.length} hint="أولوية فورية" tone="rose"/><ModuleMetric label="فواتير متعددة" value={signals.filter(s => s.type === 'duplicate_invoice').length} hint="بأكثر من دليفري" tone="violet"/><ModuleMetric label="تمت مراجعتها" value={resolved.length} hint="هذه الجلسة"/></section><div className="mt-5 grid gap-3 lg:grid-cols-2">{signals.map(s => <article key={s.key} className={`rounded-[1.6rem] border bg-white p-5 shadow-sm ${s.severity === 'high' ? 'border-rose-200' : 'border-amber-200'}`}><div className="flex items-start justify-between gap-3"><div><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${s.severity === 'high' ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700'}`}>{s.severity === 'high' ? 'خطورة عالية' : 'تحتاج مراجعة'}</span><h2 className="mt-3 font-black">{labels[s.type]}</h2><p className="mt-1 text-sm font-bold leading-6 text-slate-500">{s.description}</p></div><ShieldAlert className={s.severity === 'high' ? 'text-rose-500' : 'text-amber-500'}/></div><div className="mt-4 flex items-center justify-between border-t pt-3"><span className="text-xs font-black text-slate-600">الدليفري: {s.riderName}</span><button onClick={() => void resolve(s.key, s)} className="rounded-xl bg-[#008E92] px-3 py-2 text-xs font-black text-white">تمت المراجعة</button></div></article>)}{!signals.length && <div className="col-span-full rounded-3xl border bg-white p-16 text-center font-black text-emerald-700">لا توجد أنماط مشبوهة مفتوحة في الدورة الحالية ✓</div>}</div></AdminModuleShell>
}
