import { useEffect, useMemo, useState } from 'react'
import { BookOpenCheck, Plus, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import AdminModuleShell, { ModuleMetric } from '../../components/AdminModuleShell'
import { supabase } from '../../lib/supabase'
import { getOperationalPeriod } from '../../lib/helpers'
import type { DeliveryOrder } from '../../lib/types'

type Row = { id: string; invoiceNumber: string; customerCode: string; customerName: string; amount: number; status: 'pending' | 'matched' | 'not_found' | 'customer_mismatch'; confidence: number; matchedOrder?: DeliveryOrder }
const blank = (): Row => ({ id: crypto.randomUUID(), invoiceNumber: '', customerCode: '', customerName: '', amount: 0, status: 'pending', confidence: 0 })
export default function InvoiceNotebook() {
  const period = useMemo(() => getOperationalPeriod(), []), [orders, setOrders] = useState<DeliveryOrder[]>([]), [rows, setRows] = useState<Row[]>([blank()]), [loading, setLoading] = useState(true)
  async function load() { setLoading(true); const { data } = await supabase.from('delivery_orders').select('*').gte('delivery_date', period.start).lte('delivery_date', period.end); setOrders((data || []) as DeliveryOrder[]); setLoading(false) }
  useEffect(() => { void load() }, [])
  function update(id: string, patch: Partial<Row>) { setRows(v => v.map(r => r.id === id ? { ...r, ...patch, status: 'pending', confidence: 0 } : r)) }
  function match() { setRows(current => current.map(row => { const found = orders.find(o => String(o.invoice_number || '') === row.invoiceNumber.trim()); if (!found) return { ...row, status: 'not_found', confidence: 0 }; const orderCode = String(found.customer_code_snapshot || '').trim(), customerOk = !row.customerCode.trim() || orderCode === row.customerCode.trim(), diff = Math.abs(Number(found.invoice_amount || 0) - Number(row.amount || 0)); return { ...row, matchedOrder: found, status: customerOk ? 'matched' : 'customer_mismatch', confidence: customerOk && diff < 1 ? 100 : customerOk && diff < 10 ? 90 : 60 } })); toast.success('تمت المطابقة الفورية') }
  async function approve(row: Row) { if (!row.matchedOrder) return; const { error } = await supabase.from('delivery_orders').update({ bconnect_match_status: 'manually_approved', reconciliation_status: 'manually_approved', final_count_status: 'countable', is_countable: true, reconciliation_notes: 'اعتماد يدوي من دفتر الفواتير' }).eq('id', row.matchedOrder.id); if (error) toast.error(error.message); else { update(row.id, { status: 'matched', confidence: 100 }); toast.success('تم الاعتماد اليدوي') } }
  const summary = { matched: rows.filter(r => r.status === 'matched').length, missing: rows.filter(r => r.status === 'not_found').length, mismatch: rows.filter(r => r.status === 'customer_mismatch').length }
  return <AdminModuleShell title="الدفتر الذكي للفواتير" subtitle="إدخال سريع ومطابقة فورية مع أوردرات الدورة" icon={<BookOpenCheck/>} loading={loading} onRefresh={load} actions={<button onClick={match} className="rounded-xl bg-[#008E92] px-4 py-2 text-xs font-black text-white">طابق الآن</button>}><section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><ModuleMetric label="إجمالي السطور" value={rows.length} hint="في الدفتر"/><ModuleMetric label="متطابق" value={summary.matched} hint="تطابق مؤكد"/><ModuleMetric label="غير موجود" value={summary.missing} hint="راجع الرقم" tone="rose"/><ModuleMetric label="اختلاف عميل" value={summary.mismatch} hint="يحتاج قرار" tone="amber"/></section><div className="mt-5 overflow-hidden rounded-[2rem] border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4">#</th><th>رقم الفاتورة</th><th>كود العميل</th><th>اسم العميل</th><th>المبلغ</th><th>الحالة</th><th>الثقة</th><th>إجراء</th></tr></thead><tbody>{rows.map((r, i) => <tr key={r.id} className={`border-t ${r.status === 'matched' ? 'bg-emerald-50/40' : r.status === 'not_found' ? 'bg-rose-50/40' : r.status === 'customer_mismatch' ? 'bg-amber-50/40' : ''}`}><td className="p-3 text-slate-400">{i + 1}</td><td><input value={r.invoiceNumber} onChange={e => update(r.id, { invoiceNumber: e.target.value })} className="w-36 rounded-lg border px-2 py-2 font-black"/></td><td><input value={r.customerCode} onChange={e => update(r.id, { customerCode: e.target.value })} className="w-28 rounded-lg border px-2 py-2"/></td><td><input value={r.customerName} onChange={e => update(r.id, { customerName: e.target.value })} className="w-40 rounded-lg border px-2 py-2"/></td><td><input type="number" value={r.amount} onChange={e => update(r.id, { amount: Number(e.target.value) })} className="w-28 rounded-lg border px-2 py-2"/></td><td><Status value={r.status}/></td><td><div className="flex items-center gap-2"><div className="h-2 w-16 overflow-hidden rounded-full bg-slate-100"><div className={`h-full ${r.confidence >= 90 ? 'bg-emerald-500' : r.confidence >= 60 ? 'bg-amber-500' : 'bg-rose-500'}`} style={{ width: `${r.confidence}%` }}/></div><span className="text-xs font-black">{r.confidence}%</span></div></td><td><div className="flex gap-1">{r.matchedOrder && r.status !== 'matched' && <button onClick={() => void approve(r)} className="rounded-lg bg-teal-600 px-2 py-1 text-xs font-black text-white">اعتماد</button>}<button onClick={() => setRows(v => v.filter(x => x.id !== r.id))} className="rounded-lg bg-rose-50 p-2 text-rose-600"><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div><button onClick={() => setRows(v => [...v, blank()])} className="m-4 flex items-center gap-2 rounded-xl border border-dashed border-teal-300 px-4 py-2 text-xs font-black text-teal-700"><Plus size={15}/> إضافة سطر</button></div></AdminModuleShell>
}
function Status({ value }: { value: Row['status'] }) { const x = { pending: ['قيد الإدخال', 'bg-slate-100 text-slate-600'], matched: ['متطابق', 'bg-emerald-50 text-emerald-700'], not_found: ['غير موجود', 'bg-rose-50 text-rose-700'], customer_mismatch: ['اختلاف عميل', 'bg-amber-50 text-amber-700'] }[value]; return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${x[1]}`}>{x[0]}</span> }

