import { useEffect, useMemo, useState } from 'react'
import { Download, FileBarChart, Printer } from 'lucide-react'
import AdminModuleShell, { ModuleMetric } from '../../components/AdminModuleShell'
import { supabase } from '../../lib/supabase'
import type { DeliveryOrder, Rider } from '../../lib/types'

export default function ReportsCenter() {
  const today = new Date().toISOString().slice(0, 10), [date, setDate] = useState(today), [orders, setOrders] = useState<DeliveryOrder[]>([]), [riders, setRiders] = useState<Rider[]>([]), [loading, setLoading] = useState(true)
  async function load() { setLoading(true); const [o, r] = await Promise.all([supabase.from('delivery_orders').select('*').eq('delivery_date', date), supabase.from('riders').select('*')]); setOrders((o.data || []) as DeliveryOrder[]); setRiders((r.data || []) as Rider[]); setLoading(false) } useEffect(() => { void load() }, [date])
  const rows = useMemo(() => riders.map(r => { const ro = orders.filter(o => o.rider_id === r.id), done = ro.filter(o => o.status === 'delivered').length, failed = ro.filter(o => o.status === 'failed').length; return { name: r.name, total: ro.length, done, failed, rate: ro.length ? Math.round(done / ro.length * 100) : 0, value: ro.reduce((s, o) => s + Number(o.invoice_amount || 0), 0) } }).filter(r => r.total).sort((a, b) => b.done - a.done), [orders, riders]); const delivered = orders.filter(o => o.status === 'delivered'), failed = orders.filter(o => o.status === 'failed'), value = delivered.reduce((s, o) => s + Number(o.invoice_amount || 0), 0)
  function csv() { const content = [['الدليفري','الأوردرات','تم التسليم','فشل','نسبة النجاح','قيمة الفواتير'], ...rows.map(r => [r.name,r.total,r.done,r.failed,`${r.rate}%`,r.value])].map(x => x.join(',')).join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob(['\ufeff' + content], { type: 'text/csv;charset=utf-8' })); a.download = `dawaa-delivery-${date}.csv`; a.click(); URL.revokeObjectURL(a.href) }
  return <AdminModuleShell title="مركز التقارير" subtitle="تقرير يومي جاهز للطباعة أو التصدير" icon={<FileBarChart/>} loading={loading} onRefresh={load} actions={<><button onClick={csv} className="flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-black"><Download size={15}/> Excel/CSV</button><button onClick={() => window.print()} className="flex items-center gap-2 rounded-xl bg-[#008E92] px-3 py-2 text-xs font-black text-white"><Printer size={15}/> طباعة PDF</button></>}><div className="mb-4 rounded-2xl border bg-white p-4 print:hidden"><label className="text-xs font-black text-slate-500">تاريخ التقرير <input type="date" value={date} onChange={e => setDate(e.target.value)} className="mr-3 rounded-xl border px-3 py-2"/></label></div><section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><ModuleMetric label="إجمالي الأوردرات" value={orders.length} hint={date}/><ModuleMetric label="تم التسليم" value={delivered.length} hint={`${orders.length ? Math.round(delivered.length / orders.length * 100) : 0}%`} tone="teal"/><ModuleMetric label="فشل" value={failed.length} hint="لا يحتسب" tone="rose"/><ModuleMetric label="قيمة المسلّم" value={`${value.toLocaleString('ar-EG')} ج`} hint="إجمالي الفواتير" tone="violet"/></section><div className="mt-5 overflow-hidden rounded-[2rem] border bg-white shadow-sm"><div className="border-b p-5 text-center"><h2 className="text-xl font-black">تقرير الدليفري اليومي — صيدلية دواء</h2><p className="mt-1 text-xs font-bold text-slate-400">التاريخ: {date}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="bg-slate-50 text-xs"><tr><th className="p-4">الدليفري</th><th>الأوردرات</th><th>تم التسليم</th><th>فشل</th><th>نسبة النجاح</th><th>قيمة الفواتير</th></tr></thead><tbody>{rows.map(r => <tr key={r.name} className="border-t text-center"><td className="p-4 text-right font-black">{r.name}</td><td>{r.total}</td><td className="font-black text-emerald-700">{r.done}</td><td className="font-black text-rose-600">{r.failed}</td><td>{r.rate}%</td><td>{r.value.toLocaleString('ar-EG')} ج</td></tr>)}{!rows.length && <tr><td colSpan={6} className="p-12 text-center font-bold text-slate-400">لا توجد بيانات في هذا التاريخ</td></tr>}</tbody></table></div></div></AdminModuleShell>
}

