import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ChevronLeft, ChevronRight, Download, Pencil } from 'lucide-react'
import { useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { toast } from 'sonner'
import { getOperationalPeriod } from '../../lib/helpers'
import { supabase } from '../../lib/supabase'

type FilterKey='all'|'one'|'multi'|'review'|'delivered'|'failed'|'duplicate'|'uncounted'|'trips'
const pageSize=100
const labels:Record<FilterKey,string>={all:'كل الأوردرات',one:'أوردرات ×1',multi:'أوردرات ×1.5',review:'تحت المراجعة',delivered:'تم التسليم',failed:'فاشلة',duplicate:'مكررة',uncounted:'غير محتسبة',trips:'المشاوير'}
function rpcResult(data:any){return Array.isArray(data)?data[0]:data}
function money(v:any){return Number(v||0).toLocaleString('ar-EG',{maximumFractionDigits:0})}
function Card({label,value,tone='slate',onClick}:{label:string;value:any;tone?:'slate'|'green'|'red'|'amber'|'purple'|'blue';onClick?:()=>void}){const cls={slate:'bg-white text-slate-800',green:'bg-emerald-50 text-emerald-800',red:'bg-rose-50 text-rose-800',amber:'bg-amber-50 text-amber-800',purple:'bg-purple-50 text-purple-800',blue:'bg-sky-50 text-sky-800'}[tone];return <button type="button" onClick={onClick} className={`rounded-3xl border border-slate-100 p-4 text-right shadow-sm ${cls}`}><p className="text-xs font-black opacity-70">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></button>}

export default function RiderPerformanceDetailFast(){
  const {riderId}=useParams()
  const navigate=useNavigate()
  const [params,setParams]=useSearchParams()
  const period=getOperationalPeriod()
  const from=params.get('from')||period.start
  const to=params.get('to')||period.end
  const filter=((params.get('filter')==='multiplier'?'multi':params.get('filter'))||'all') as FilterKey
  const [page,setPage]=useState(0)
  const [payload,setPayload]=useState<any>(null)
  const [loading,setLoading]=useState(true)
  const [edit,setEdit]=useState<any|null>(null)
  const [draft,setDraft]=useState<any>({})
  const [saving,setSaving]=useState(false)

  useEffect(()=>setPage(0),[filter,from,to,riderId])
  async function load(){if(!riderId)return;try{setLoading(true);const {data,error}=await supabase.rpc('rider_performance_detail_fast',{p_rider_id:riderId,p_from:from,p_to:to,p_filter:filter,p_limit:pageSize,p_offset:page*pageSize});if(error)throw error;const result=rpcResult(data);if(!result?.success)throw new Error(result?.message||'تعذر تحميل التقرير');setPayload(result)}catch(error:any){toast.error(error?.message||'فشل تحميل تقرير المندوب')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[riderId,from,to,filter,page])

  const rider=payload?.rider||{}
  const summary=payload?.summary||{}
  const rows=Array.isArray(payload?.rows)?payload.rows:[]
  const totalFiltered=Number(payload?.total_filtered||0)
  const pages=Math.max(1,Math.ceil(totalFiltered/pageSize))
  const cards=useMemo(()=>[
    ['كل الأوردرات',summary.total||0,'all','blue'],['×1',summary.one_orders||0,'one','slate'],['×1.5',summary.multi_orders||0,'multi','purple'],['تحت المراجعة',summary.review_orders||0,'review','amber'],['تم التسليم',summary.delivered||0,'delivered','green'],['فشل',summary.failed||0,'failed','red'],['مكرر',summary.duplicate||0,'duplicate','red'],['غير محتسب',summary.uncounted||0,'uncounted','amber'],['المشاوير',summary.total_trips||0,'trips','blue']
  ] as any[],[summary])

  function setFilter(next:FilterKey){const p=new URLSearchParams(params);next==='all'?p.delete('filter'):p.set('filter',next==='multi'?'multiplier':next);setParams(p)}
  function changeRange(key:'from'|'to',value:string){const p=new URLSearchParams(params);p.set(key,value);setParams(p)}
  function openEdit(row:any){setEdit(row);setDraft({invoice:row.invoice_number||row.invoice_no||'',customer:row.customer_name||row.customer_name_snapshot||'',phone:row.customer_phone||row.customer_phone_snapshot||'',address:row.customer_address||row.customer_address_snapshot||'',amount:row.invoice_amount||row.invoice_value||0,status:row.status||'registered',multiplier:String(row.order_multiplier||1),note:''})}
  async function saveEdit(){if(!edit)return;try{setSaving(true);const m=Number(draft.multiplier||1)||1;const amount=Number(draft.amount||0)||0;const patch:any={invoice_number:String(draft.invoice||'').trim()||null,invoice_no:String(draft.invoice||'').trim()||null,customer_name:String(draft.customer||'').trim()||null,customer_name_snapshot:String(draft.customer||'').trim()||null,customer_phone:String(draft.phone||'').trim()||null,customer_phone_snapshot:String(draft.phone||'').trim()||null,customer_address:String(draft.address||'').trim()||null,customer_address_snapshot:String(draft.address||'').trim()||null,invoice_amount:amount,invoice_value:amount,status:draft.status,order_multiplier:m,is_multiplier_order:m>=1.5,updated_at:new Date().toISOString()};if(String(draft.note||'').trim())patch.notes=`${edit.notes?`${edit.notes}\n`:''}تعديل المدير: ${draft.note}`;const {error}=await supabase.from('delivery_orders').update(patch).eq('id',edit.id);if(error)throw error;toast.success('تم تعديل الأوردر');setEdit(null);void load()}catch(error:any){toast.error(error?.message||'تعذر التعديل')}finally{setSaving(false)}}

  return <div className="min-h-screen bg-[#F3F7F8]" dir="rtl">
    <header className="sticky top-0 z-20 border-b bg-white/95 px-4 py-3 shadow-sm"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3"><button onClick={()=>navigate('/admin/performance')} className="flex items-center gap-2 rounded-2xl bg-slate-100 px-3 py-2 text-sm font-bold"><ArrowLeft size={16}/> رجوع</button><div className="text-center"><p className="text-lg font-black">تقرير {rider.name||rider.username||'الدليفري'} · Fast</p><p className="text-xs font-bold text-slate-400">{from} → {to} · تحميل على دفعات</p></div><button onClick={()=>window.print()} className="flex items-center gap-2 rounded-2xl bg-[#008E92] px-4 py-2 text-sm font-black text-white"><Download size={16}/> PDF</button></div></header>
    <main className="mx-auto max-w-7xl space-y-4 p-4">
      <section className="rounded-3xl bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-black">{rider.name||rider.username||'دليفري'}</h1><p className="mt-1 text-sm font-bold text-slate-500">{rider.branch_name||'—'} · {rider.status||'active'}</p></div><div className="grid grid-cols-2 gap-2"><label className="text-xs font-black text-slate-500">من<input type="date" value={from} onChange={e=>changeRange('from',e.target.value)} className="mt-1 block rounded-xl border p-2"/></label><label className="text-xs font-black text-slate-500">إلى<input type="date" value={to} onChange={e=>changeRange('to',e.target.value)} className="mt-1 block rounded-xl border p-2"/></label></div></div></section>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([l,v,f,t])=><Card key={f} label={l} value={v} tone={t} onClick={()=>setFilter(f)}/>)}</section>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Card label="أيام الحضور" value={summary.attendance_days||0}/><Card label="ساعات الحضور" value={`${Number(summary.attendance_hours||0).toFixed(1)} س`} tone="blue"/><Card label="خصومات معتمدة" value={`${money(summary.deductions)} ج`} tone="red"/><Card label="مكافآت معتمدة" value={`${money(summary.rewards)} ج`} tone="green"/><Card label="صافي القيمة" value={`${money(summary.net)} ج`} tone="purple"/><Card label="مؤشر المخاطر" value={summary.risk_score||0} tone="amber"/></section>
      <section className="rounded-3xl border bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-lg font-black">{labels[filter]}</h2><p className="text-xs font-bold text-slate-400">{totalFiltered.toLocaleString('en-US')} سجل</p></div>{filter!=='trips'&&<span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-black text-teal-700">الأوردرات</span>}</div>{loading?<div className="py-12 text-center font-black text-slate-400">جاري تحميل الصفحة...</div>:rows.length===0?<div className="py-12 text-center font-black text-slate-400">لا توجد بيانات</div>:<div className="space-y-2">{rows.map((row:any)=>filter==='trips'?<article key={row.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><div><b>{row.from_label||'—'} ← {row.to_label||'—'}</b><p className="mt-1 text-xs font-bold text-slate-500">{row.reason||'بدون سبب'} · {row.trip_type||'مشوار'}</p></div><span className="text-xs font-black text-teal-700">{row.status||row.review_status||'—'}</span></div></article>:<article key={row.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><b>فاتورة {row.invoice_number||row.invoice_no||'—'}</b>{row.is_multi&&<span className="rounded-full bg-purple-100 px-2 py-0.5 text-[10px] font-black text-purple-700">×1.5</span>}{row.is_duplicate&&<span className="rounded-full bg-rose-100 px-2 py-0.5 text-[10px] font-black text-rose-700">مكرر</span>}</div><p className="mt-1 text-xs font-bold text-slate-500">{row.customer_name_snapshot||row.customer_name||'عميل غير محدد'} · {money(row.invoice_amount||row.invoice_value)} ج</p><p className="mt-1 text-[11px] font-bold text-slate-400">{row.delivery_date||row.work_date||'—'} · {row.status||'—'}</p></div><button onClick={()=>openEdit(row)} className="rounded-xl bg-white p-2 text-slate-600 shadow-sm"><Pencil size={16}/></button></div></article>)}</div>}</section>
      <section className="flex items-center justify-between rounded-2xl bg-white p-3 shadow-sm"><button disabled={page===0||loading} onClick={()=>setPage(p=>Math.max(0,p-1))} className="inline-flex items-center gap-1 rounded-xl bg-slate-100 px-3 py-2 text-xs font-black disabled:opacity-40"><ChevronRight size={15}/> السابق</button><p className="text-xs font-black text-slate-500">صفحة {page+1} من {pages}</p><button disabled={page+1>=pages||loading} onClick={()=>setPage(p=>p+1)} className="inline-flex items-center gap-1 rounded-xl bg-slate-100 px-3 py-2 text-xs font-black disabled:opacity-40">التالي <ChevronLeft size={15}/></button></section>
      <section className="rounded-2xl border border-teal-100 bg-teal-50 p-3 text-xs font-bold text-teal-900">النسخة التفصيلية القديمة محفوظة مؤقتًا في <button onClick={()=>navigate(`/admin/riders/${riderId}/performance-legacy?from=${from}&to=${to}`)} className="font-black underline">المسار القديم</button> لو احتجت مقارنة أي تفاصيل أثناء الانتقال.</section>
    </main>
    {edit&&<div className="fixed inset-0 z-50 bg-slate-950/50 p-3"><div className="mx-auto flex h-full max-w-xl items-center"><section className="max-h-[92vh] w-full overflow-y-auto rounded-3xl bg-white p-5"><h2 className="text-xl font-black">تعديل الأوردر</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input value={draft.invoice||''} onChange={e=>setDraft({...draft,invoice:e.target.value})} className="rounded-xl border p-3" placeholder="رقم الفاتورة"/><input value={draft.amount||''} onChange={e=>setDraft({...draft,amount:e.target.value})} className="rounded-xl border p-3" placeholder="القيمة"/><input value={draft.customer||''} onChange={e=>setDraft({...draft,customer:e.target.value})} className="rounded-xl border p-3" placeholder="العميل"/><input value={draft.phone||''} onChange={e=>setDraft({...draft,phone:e.target.value})} className="rounded-xl border p-3" placeholder="الهاتف"/><input value={draft.address||''} onChange={e=>setDraft({...draft,address:e.target.value})} className="rounded-xl border p-3 sm:col-span-2" placeholder="العنوان"/><select value={draft.status||'registered'} onChange={e=>setDraft({...draft,status:e.target.value})} className="rounded-xl border p-3"><option value="registered">مسجل</option><option value="delivered">تم التسليم</option><option value="failed">فشل</option></select><select value={draft.multiplier||'1'} onChange={e=>setDraft({...draft,multiplier:e.target.value})} className="rounded-xl border p-3"><option value="1">×1</option><option value="1.5">×1.5</option></select><textarea value={draft.note||''} onChange={e=>setDraft({...draft,note:e.target.value})} rows={3} className="rounded-xl border p-3 sm:col-span-2" placeholder="سبب/ملاحظة التعديل"/></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setEdit(null)} className="rounded-xl bg-slate-100 py-3 font-black">إلغاء</button><button disabled={saving} onClick={()=>void saveEdit()} className="rounded-xl bg-[#008E92] py-3 font-black text-white disabled:opacity-50">{saving?'جاري الحفظ...':'حفظ'}</button></div></section></div></div>}
  </div>
}
